### ISSUE TITLE
Unable to have multiple messages

### ISSUE THREAD

**Issue by sunnykeerthi** [PrajvalRaval/salesforce-live-agent-console-app#1]
Hi Prajval,

Firstly, thank you very much for this awesome, Interactive Live Agent app. 
I wanted to bring something to your attention, Not sure if it is a bug or you didn't have it added.

- When we are doing a 1:1 messaging session (customer sends 1 message and agent sends 1 message), this is working brilliant

- When the agent wants to send multiple messages at the same time, it is not working.

**Here is an example:**

_1:1 messages_ **This is working**
A: Hi user How Can I help you?
U: I'm having an issue with my computer.
A: let me create a case for you.
U: thank you.

_many:many messages_ **This is not working**
A: Hi user How Can I help you?
U: I'm having an issue with my computer.
A: let me create a case for you.
A: Can you please give me a minute?
U: thank you.

Can you please give me a workaround for this scenario?

Thanks

**Comment by PrajvalRaval** [comment]
Hi @sunnykeerthi, it's not a bug rather it was intentionally left out. Actually, this app was developed just to be a demo/test for Salesforce Liveagent APIs. The actual app that was developed for RocketChat Livechat, contains the features such as multiple messages, queue support etc., you can find the repo [here](https://github.com/PrajvalRaval/Apps.Salesforce.LiveAgent).
